### 내 동네 설정
POST localhost:8080/users/locations/1
X-AUTH-TOKEN: eyJyZWdEYXRlIjoxNjg0NTYyOTYzNDU1LCJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9VU0VSIn1dLCJlbWFpbCI6InRlc3QwMUBuYXZlci5jb20iLCJleHAiOjE2ODcxNTQ5NjN9.CW_kp2ermuA2RmubfCMiaOWOFJtvosZBnVBsTdAp9C4