### 회원 프로필 수정
PUT localhost:8080/users
Content-Type: application/json
X-AUTH-TOKEN:  eyJyZWdEYXRlIjoxNjg0MzE2ODMzMzc5LCJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9VU0VSIn1dLCJlbWFpbCI6InRlc3QwMUBuYXZlci5jb20iLCJleHAiOjE2ODY5MDg4MzN9.CAJyUM-jg4TeyOGEbEuwxC3omLcm4FaHeJ7_ZOyU9QU

{
  "nickname" : "newNickname",
  "imageUrl" : "c://images/users/1/이미지이름"
}

### 관심 카테고리 설정 - 삭제
POST localhost:8080/users/categories/1/delete
Content-Type: application/json
X-AUTH-TOKEN:  eyJyZWdEYXRlIjoxNjk0NTkxMTU4MjQxLCJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9VU0VSIn1dLCJlbWFpbCI6InRlc3QwMUBuYXZlci5jb20iLCJleHAiOjE2OTcxODMxNTh9.KNsFOUe-7amqExEblCRyADLuho7xt2aBbK1q5xCok1M

### 관심 카테고리 설정 - 추가
POST localhost:8080/users/categories/1/add
Content-Type: application/json
X-AUTH-TOKEN:  eyJyZWdEYXRlIjoxNjg0MzE2ODMzMzc5LCJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9VU0VSIn1dLCJlbWFpbCI6InRlc3QwMUBuYXZlci5jb20iLCJleHAiOjE2ODY5MDg4MzN9.CAJyUM-jg4TeyOGEbEuwxC3omLcm4FaHeJ7_ZOyU9QU

### 내 동네 설정
POST localhost:8080/users/locations/2
X-AUTH-TOKEN: eyJyZWdEYXRlIjoxNjk1NzExMjY1MDExLCJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9VU0VSIn1dLCJlbWFpbCI6InRlc3QwMUBuYXZlci5jb20iLCJleHAiOjE2OTgzMDMyNjV9.K2ZffmmZimCWmXMcFgcQq5gmH47gDBafq-bqPuLLhgY